# Generated by Django 5.0.6 on 2026-05-02 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['code'], name='policies_po_code_d8a35a_idx')],
            },
        ),
        migrations.CreateModel(
            name='PolicyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('policy_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='policies.policytype')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_at_entry', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('premium', models.DecimalField(decimal_places=2, max_digits=12)),
                ('premium_frequency', models.CharField(choices=[('annual', 'Annual'), ('semi', 'Semi-Annual'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly')], default='annual', max_length=16)),
                ('premium_term', models.PositiveSmallIntegerField()),
                ('policy_term', models.PositiveSmallIntegerField()),
                ('sum_assured', models.DecimalField(decimal_places=2, max_digits=14)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('result', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to=settings.AUTH_USER_MODEL)),
                ('policy_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='policies.policytype')),
                ('policy_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='policies.policyversion')),
                ('riders', models.ManyToManyField(blank=True, to='policies.rider')),
            ],
        ),
        migrations.AddIndex(
            model_name='policyversion',
            index=models.Index(fields=['policy_type', 'effective_from'], name='policies_po_policy__d0920e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='policyversion',
            unique_together={('policy_type', 'version')},
        ),
        migrations.AddIndex(
            model_name='policyquote',
            index=models.Index(fields=['user', '-created_at'], name='policies_po_user_id_bc7537_idx'),
        ),
        migrations.AddIndex(
            model_name='policyquote',
            index=models.Index(fields=['policy_type', '-created_at'], name='policies_po_policy__b8a439_idx'),
        ),
        migrations.AddConstraint(
            model_name='policyquote',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('user', 'idempotency_key'), name='uniq_user_idempotency_key'),
        ),
    ]
